export const twitter = {
  TWITTER_API_KEY: 'ttreZe5HpPjoVFgGE7wl5vZQw',
  TWITTER_API_SECRET: 'ty8YSoDFqdqV5ronBIiKYX6Yvz4wHj4mava0eab9xq8S2ZYrQv',
  TWITTER_BEARER_TOKEN:
    'AAAAAAAAAAAAAAAAAAAAANV%2FWwEAAAAAnWm0evEemaGcztJfKWQs4MqAvHs%3DGRNP9xi2RNLaqS0JdMRAEPIDCdXHTpKayDcuXnWBChLfgoCAiL',
}
